export enum ServiceProviderToken {
    ADMIN_SERVICE = 'ADMIN_SERVICE',
    AUDIT_SERVICE = 'AUDIT_SERVICE',
    AUTH_SERVICE = 'AUTH_SERVICE',
    BUSINESS_SERVICE = 'BUSINESS_SERVICE',
    BOOKING_SERVICE = 'BOOKING_SERVICE',
    BANKING_SERVICE = 'BANKING_SERVICE',
    RESOURCE_SERVICE = 'RESOURCE_SERVICE',
    INVOICE_SERVICE = 'INVOICE_SERVICE',
    NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE',
    KYC_SERVICE = 'KYC_SERVICE',
    SEARCH_SERVICE = 'SEARCH_SERVICE',
}
